[package]
name = "mosslight-game-hub"
version = "0.25.0"
description = "Mosslight Game Hub"
authors = ["Mosslight Studios"]
edition = "2021"

[lib]
name = "mosslight_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-dialog = "2"
tauri-plugin-http = "2"
tauri-plugin-opener = "2"
tauri-plugin-process = "2"
tauri-plugin-updater = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
keyring = { version = "3", features = ["apple-native", "windows-native", "sync-secret-service"] }
which = "7"
dirs = "6"
urlencoding = "2"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
