import { useCallback, useEffect, useMemo, useState } from 'react';
import type { Hub } from '../core/store';
import type { Project, ProjectDoc } from '../core/types';
import { ago, baseName, fmtSize, uid, now } from '../core/util';
import { fileSrc, findFiles, isDesktop, launchPath, openExternal, pickFiles, type FoundFile } from '../platform';
import { deviceId, localFolder } from '../sync/device';
import { useImageSrc } from '../sync/images';

const IMAGE_EXTS = ['png', 'jpg', 'jpeg', 'webp', 'gif', 'bmp', 'avif'];
const DOC_EXTS = ['pdf'];
const PAGE = 120;

export interface GalleryItem {
  id: string;
  /** Local path, or a synced img: reference for agent-generated art. */
  src: string;
  name: string;
  group: string;
  caption?: string;
  ts?: number;
  /** Comes from a folder on this computer. */
  local: boolean;
  /** Copied into sync, so the phone and other computers can see it. */
  shared?: boolean;
}

const parentOf = (p: string) => p.replace(/[\\/][^\\/]+$/, '');

/** Folder path → a readable group name ("Art/Concepts" → "Concepts", kept unique). */
function groupName(folder: string, seen: Map<string, string>) {
  if (!folder) return 'Project root';
  const parts = folder.split('/').filter(Boolean);
  const last = parts[parts.length - 1];
  const taken = seen.get(last.toLowerCase());
  if (taken && taken !== folder) return parts.slice(-2).join(' / ');
  seen.set(last.toLowerCase(), folder);
  return last;
}

/** Scans the project folder for images (desktop) and merges in agent-generated art. */
export function useProjectImages(p: Project) {
  const [found, setFound] = useState<FoundFile[] | null>(null);
  const [error, setError] = useState('');
  const [scanning, setScanning] = useState(false);
  const lf = localFolder(p);

  const scan = useCallback(async () => {
    if (!lf?.path || !isDesktop) { setFound([]); return; }
    setScanning(true);
    setError('');
    try {
      setFound(await findFiles(lf.path, IMAGE_EXTS, 4000));
    } catch (e) {
      setError(String((e as Error)?.message || e));
      setFound([]);
    } finally {
      setScanning(false);
    }
  }, [lf?.path]);

  useEffect(() => { void scan(); }, [scan]);

  const items = useMemo<GalleryItem[]>(() => {
    const seen = new Map<string, string>();
    const shared = p.sharedArt || [];
    const sharedFrom = new Map(shared.filter(s => s.from).map(s => [s.from!, s]));
    const fromDisk = (found || []).map(f => ({ id: f.path, src: f.path, name: f.name, group: groupName(f.folder, seen), ts: f.modified, local: true, shared: sharedFrom.has(f.path) }));
    const onDisk = new Set(fromDisk.map(f => f.src));
    // On the phone (or a computer without the folder) the shared copies are the art.
    const fromSync = shared.filter(s => !s.from || !onDisk.has(s.from)).map(s => ({ id: s.id, src: s.ref, name: s.name, group: s.group, ts: s.ts, local: false, shared: true }));
    const generated = p.art.filter(a => a.imagePath).map(a => ({ id: a.id, src: a.imagePath!, name: a.title, group: 'Generated by Grok', caption: a.prompt, ts: a.ts, local: false, shared: true }));
    return [...generated, ...fromDisk, ...fromSync];
  }, [found, p.art, p.sharedArt]);

  const groups = useMemo(() => {
    const m = new Map<string, number>();
    for (const i of items) m.set(i.group, (m.get(i.group) || 0) + 1);
    return [...m.entries()].sort((a, b) => (a[0] === 'Generated by Grok' ? -1 : b[0] === 'Generated by Grok' ? 1 : a[0].localeCompare(b[0])));
  }, [items]);

  return { items, groups, scanning, error, rescan: scan, hasFolder: !!lf?.path };
}

function Thumb({ item, onClick }: { item: GalleryItem; onClick: () => void }) {
  const url = useImageSrc(item.src);
  return (
    <button onClick={onClick} className="card hover-line" style={{ padding: 0, overflow: 'hidden', border: '1px solid var(--line)', borderRadius: 12, background: 'var(--well)', display: 'flex', flexDirection: 'column' }}>
      <span style={{ position: 'relative', aspectRatio: '4/3', width: '100%', background: 'var(--well)', display: 'block' }}>
        {url && <img src={url} alt={item.name} loading="lazy" style={{ position: 'absolute', inset: 0, width: '100%', height: '100%', objectFit: 'cover' }} />}
      </span>
      <span className="ellipsis" style={{ padding: '7px 9px', fontSize: 11, color: 'var(--text-2)', width: '100%', textAlign: 'left' }}>{item.name}</span>
    </button>
  );
}

/** Full-screen image viewer with keyboard navigation. */
function Lightbox({ items, index, onIndex, onClose, hub, p }: { items: GalleryItem[]; index: number; onIndex: (i: number) => void; onClose: () => void; hub: Hub; p: Project }) {
  const item = items[index];
  const url = useImageSrc(item?.src);
  useEffect(() => {
    const k = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
      if (e.key === 'ArrowRight') onIndex(Math.min(items.length - 1, index + 1));
      if (e.key === 'ArrowLeft') onIndex(Math.max(0, index - 1));
    };
    window.addEventListener('keydown', k);
    return () => window.removeEventListener('keydown', k);
  }, [index, items.length, onIndex, onClose]);
  if (!item) return null;
  const arrow = { background: 'var(--chip-bg)', border: '1px solid var(--line-2)', color: 'var(--chip-text)', borderRadius: 999, width: 42, height: 42, fontSize: 18, flex: 'none' } as const;
  return (
    <div className="scrim" onClick={onClose} style={{ padding: 0, zIndex: 40 }}>
      <div onClick={e => e.stopPropagation()} style={{ width: '100%', height: '100%', display: 'grid', gridTemplateRows: 'auto minmax(0,1fr) auto', gap: 10, padding: 16 }}>
        <div className="row wrap" style={{ gap: 10 }}>
          <span style={{ fontWeight: 600, fontSize: 14 }}>{item.name}</span>
          <span className="mono" style={{ fontSize: 11, color: 'var(--muted)' }}>{item.group}{item.ts ? ` · ${ago(item.ts)}` : ''}</span>
          <span style={{ flex: 1 }} />
          <span className="mono" style={{ fontSize: 11, color: 'var(--muted)' }}>{index + 1} / {items.length}</span>
          <button className="btn-ghost" style={{ padding: '6px 10px', fontSize: 12 }} onClick={() => { hub.setCoverFrom(p.id, item.src); onClose(); }}>Use as cover</button>
          {item.local && isDesktop && <button className="btn-ghost" style={{ padding: '6px 10px', fontSize: 12 }} onClick={() => void launchPath(parentOf(item.src)).catch(() => {})}>Show in folder</button>}
          <button className="x" style={{ fontSize: 22 }} onClick={onClose}>×</button>
        </div>
        <div className="row" style={{ gap: 10, minHeight: 0, justifyContent: 'center' }}>
          <button style={{ ...arrow, opacity: index ? 1 : 0.3 }} disabled={!index} onClick={() => onIndex(index - 1)}>‹</button>
          <div style={{ flex: 1, minWidth: 0, height: '100%', display: 'grid', placeItems: 'center' }}>
            {url && <img src={url} alt={item.name} style={{ maxWidth: '100%', maxHeight: '100%', objectFit: 'contain', borderRadius: 10 }} />}
          </div>
          <button style={{ ...arrow, opacity: index < items.length - 1 ? 1 : 0.3 }} disabled={index >= items.length - 1} onClick={() => onIndex(index + 1)}>›</button>
        </div>
        <div className="mono ellipsis" style={{ fontSize: 11, color: 'var(--dim)', textAlign: 'center' }}>{item.caption || item.src}</div>
      </div>
    </div>
  );
}

/** Project → Art: every image in the project folder, grouped by its folder. */
export function ArtTab({ hub, p }: { hub: Hub; p: Project }) {
  const { items, groups, scanning, error, rescan, hasFolder } = useProjectImages(p);
  const [group, setGroup] = useState<string | null>(null);
  const [q, setQ] = useState('');
  const [limit, setLimit] = useState(PAGE);
  const [open, setOpen] = useState<number | null>(null);
  const shown = useMemo(() => items.filter(i => (!group || i.group === group) && (!q || i.name.toLowerCase().includes(q.toLowerCase()))), [items, group, q]);
  useEffect(() => { setLimit(PAGE); }, [group, q]);

  return (
    <>
      <div className="row wrap" style={{ justifyContent: 'space-between', marginBottom: 14, gap: 12 }}>
        <p style={{ margin: 0, color: 'var(--muted)', fontSize: 13, maxWidth: '62ch' }}>
          {hasFolder
            ? <>Every image in <span className="mono">{localFolder(p)?.path}</span>, grouped by folder — characters, maps, cars, concepts. Click one to view it or make it the cover.</>
            : isDesktop ? 'Link a local folder (Open local folder in the Library) to see this project\'s art here.' : 'Art from the project folder shows on the computer that has it. Grok\'s generated art shows on every device.'}
        </p>
        <div className="row wrap">
          {hasFolder && <button className="btn" style={{ fontSize: 12, padding: '7px 12px' }} disabled={scanning} onClick={() => void rescan()}>{scanning ? 'Scanning…' : 'Rescan folder'}</button>}
          <button style={{ background: 'var(--ag-grok)', border: 0, color: 'var(--on-agent)', borderRadius: 10, padding: '9px 14px', fontSize: 13, fontWeight: 600 }} onClick={() => hub.ask(`Generate three new concept art pieces for ${p.name} exploring a different mood than what we have.`, 'grok')}>Ask Grok for more art</button>
        </div>
      </div>
      {error && <p style={{ color: 'var(--danger)', fontSize: 13 }}>{error}</p>}
      {groups.length > 0 && (
        <div className="row wrap" style={{ gap: 8, marginBottom: 14 }}>
          <button className={'pill' + (group === null ? ' on' : '')} onClick={() => setGroup(null)}>All <span className="mono" style={{ fontSize: 10, opacity: .7 }}>{items.length}</span></button>
          {groups.map(([g, n]) => <button key={g} className={'pill' + (group === g ? ' on' : '')} onClick={() => setGroup(g)}>{g} <span className="mono" style={{ fontSize: 10, opacity: .7 }}>{n}</span></button>)}
          <input value={q} onChange={e => setQ(e.target.value)} placeholder="Search file names" style={{ marginLeft: 'auto', background: 'var(--panel)', border: '1px solid var(--line-2)', borderRadius: 10, padding: '7px 12px', fontSize: 12, minWidth: 180 }} />
        </div>
      )}
      {isDesktop && !!items.length && (() => {
        const scope = shown.filter(i => i.local);
        const unshared = scope.filter(i => !i.shared);
        const label = group ? `“${group}”` : 'everything here';
        if (hub.sharing) return <p style={{ fontSize: 12, color: 'var(--accent)', marginTop: -4, marginBottom: 12 }}>Sharing… {hub.sharing.done} / {hub.sharing.total}</p>;
        if (!scope.length) return null;
        return (
          <div className="row wrap" style={{ gap: 8, marginTop: -4, marginBottom: 12, fontSize: 12, color: 'var(--muted)' }}>
            {unshared.length
              ? <><button className="btn" style={{ fontSize: 12, padding: '6px 12px' }} onClick={() => void hub.shareArt(p.id, unshared)}>Share {unshared.length} image{unshared.length === 1 ? '' : 's'} with my devices</button><span>so {label} shows on your phone too</span></>
              : <><span style={{ color: 'var(--green)', fontWeight: 600 }}>✓ Shared with your devices</span>{group && <button className="link" style={{ color: 'var(--muted)' }} onClick={() => hub.unshareArt(p.id, group)}>Stop sharing {group}</button>}</>}
          </div>
        );
      })()}
      {scanning && !items.length && <p style={{ color: 'var(--muted)', fontSize: 13 }}>Looking for art…</p>}
      {!scanning && !items.length && <p style={{ color: 'var(--muted)', fontSize: 13 }}>No images found yet.{hasFolder ? ' Drop art into the project folder, or ask Grok for concept art.' : ''}</p>}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(180px, 1fr))', gap: 12 }}>
        {shown.slice(0, limit).map((it, i) => <Thumb key={it.id} item={it} onClick={() => setOpen(i)} />)}
      </div>
      {shown.length > limit && <button className="btn" style={{ marginTop: 14 }} onClick={() => setLimit(l => l + PAGE)}>Show {Math.min(PAGE, shown.length - limit)} more ({shown.length - limit} left)</button>}
      {open !== null && <Lightbox items={shown} index={open} onIndex={setOpen} onClose={() => setOpen(null)} hub={hub} p={p} />}
    </>
  );
}

// ── Guides (play guides, design docs, PDFs) ───────────────────────────────────

function DocViewer({ doc, onClose }: { doc: ProjectDoc; onClose: () => void }) {
  // Prefer the synced copy when this device doesn't hold the file.
  const mine = !doc.device || doc.device === deviceId;
  const synced = useImageSrc(doc.ref);
  const url = (mine && isDesktop ? fileSrc(doc.path) : undefined) || synced || fileSrc(doc.path);
  const [failed, setFailed] = useState(false);
  return (
    <div className="scrim" onClick={onClose} style={{ padding: 0, zIndex: 40 }}>
      <div onClick={e => e.stopPropagation()} style={{ width: '100%', height: '100%', display: 'grid', gridTemplateRows: 'auto minmax(0,1fr)', gap: 10, padding: 16 }}>
        <div className="row wrap" style={{ gap: 10 }}>
          <span style={{ fontWeight: 600, fontSize: 14 }}>{doc.name}</span>
          <span style={{ flex: 1 }} />
          {isDesktop && <button className="btn-ghost" style={{ padding: '6px 10px', fontSize: 12 }} onClick={() => void launchPath(doc.path).catch(() => {})}>Open outside Mosslight</button>}
          <button className="x" style={{ fontSize: 22 }} onClick={onClose}>×</button>
        </div>
        <div style={{ minHeight: 0, background: 'var(--panel-solid)', borderRadius: 12, overflow: 'hidden' }}>
          {doc.kind === 'image' ? <img src={url} alt={doc.name} style={{ width: '100%', height: '100%', objectFit: 'contain' }} />
            : failed ? (
              <div style={{ display: 'grid', placeItems: 'center', height: '100%', padding: 24, textAlign: 'center', color: 'var(--muted)', fontSize: 13 }}>
                This document can't be shown inside Mosslight.{isDesktop ? ' Use "Open outside Mosslight" above.' : ''}
              </div>
            ) : <iframe title={doc.name} src={url} onError={() => setFailed(true)} style={{ width: '100%', height: '100%', border: 0, background: '#fff' }} />}
        </div>
      </div>
    </div>
  );
}

const docKind = (name: string): ProjectDoc['kind'] => (/\.pdf$/i.test(name) ? 'pdf' : /\.(png|jpe?g|webp|gif)$/i.test(name) ? 'image' : /\.(md|txt)$/i.test(name) ? 'text' : 'other');

/** Project → Guides: play guides and design PDFs, found in the folder or added by hand. */
export function GuidesTab({ hub, p }: { hub: Hub; p: Project }) {
  const [found, setFound] = useState<FoundFile[]>([]);
  const [scanning, setScanning] = useState(false);
  const [open, setOpen] = useState<ProjectDoc | null>(null);
  const lf = localFolder(p);
  const added = p.docs || [];

  const scan = useCallback(async () => {
    if (!lf?.path || !isDesktop) return;
    setScanning(true);
    try { setFound(await findFiles(lf.path, DOC_EXTS, 200)); } catch { /* ignore */ } finally { setScanning(false); }
  }, [lf?.path]);
  useEffect(() => { void scan(); }, [scan]);

  const addFiles = async () => {
    const paths = await pickFiles();
    if (!paths.length) return;
    hub.updProj(p.id, q => ({
      ...q,
      docs: [...paths.filter(x => !(q.docs || []).some(d => d.path === x)).map(x => ({ id: uid(), name: baseName(x), path: x, device: deviceId, kind: docKind(x), ts: now() })), ...(q.docs || [])],
    }));
  };

  const fromFolder: ProjectDoc[] = found
    .filter(f => !added.some(d => d.path === f.path))
    .map(f => ({ id: f.path, name: f.name, path: f.path, device: deviceId, kind: docKind(f.name), size: f.size, ts: f.modified }));
  const all = [...added, ...fromFolder];

  return (
    <>
      <div className="row wrap" style={{ justifyContent: 'space-between', marginBottom: 14, gap: 12 }}>
        <p style={{ margin: 0, color: 'var(--muted)', fontSize: 13, maxWidth: '62ch' }}>
          Play guides, design docs and reference PDFs. {lf?.path ? 'PDFs in the project folder show up automatically.' : ''} Click one to read it inside Mosslight.
        </p>
        {isDesktop && <button className="btn-accent" onClick={() => void addFiles()}>Add a document</button>}
      </div>
      {scanning && !all.length && <p style={{ color: 'var(--muted)', fontSize: 13 }}>Looking for documents…</p>}
      {!scanning && !all.length && <p style={{ color: 'var(--muted)', fontSize: 13 }}>No documents yet.{isDesktop ? ' Use “Add a document” for your play guide.' : ' Add documents from the desktop app.'}</p>}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(260px, 1fr))', gap: 12 }}>
        {all.map(d => {
          const mine = !d.device || d.device === deviceId;
          return (
            <div key={d.id} className="card hover-line" style={{ padding: 14, display: 'flex', flexDirection: 'column', gap: 6 }}>
              <div className="row" style={{ gap: 10 }}>
                <span style={{ fontSize: 22 }}>{d.kind === 'pdf' ? '📕' : d.kind === 'image' ? '🖼' : '📄'}</span>
                <span className="ellipsis" style={{ fontWeight: 600, fontSize: 13, flex: 1 }} title={d.path}>{d.name}</span>
                {added.some(x => x.id === d.id) && <button className="x" title="Remove from this list" onClick={() => hub.updProj(p.id, q => ({ ...q, docs: (q.docs || []).filter(x => x.id !== d.id) }))}>×</button>}
              </div>
              <span className="mono" style={{ fontSize: 10, color: 'var(--dim)' }}>{d.size ? fmtSize(d.size) + ' · ' : ''}{d.ts ? ago(d.ts) : ''}</span>
              <div className="row wrap" style={{ gap: 6, marginTop: 'auto', paddingTop: 6 }}>
                {d.ref || mine || /^https?:/.test(d.path)
                  ? <button className="btn-ghost" style={{ padding: '5px 10px', fontSize: 11 }} onClick={() => (/^https?:/.test(d.path) ? void openExternal(d.path) : setOpen(d))}>Read</button>
                  : <span style={{ fontSize: 11, color: 'var(--muted)' }}>On {hub.deviceName(d.device)}</span>}
                {mine && isDesktop && <button className="btn-ghost" style={{ padding: '5px 10px', fontSize: 11 }} onClick={() => void launchPath(d.path).catch(() => {})}>Open externally</button>}
                {mine && isDesktop && (d.ref
                  ? <span style={{ fontSize: 11, color: 'var(--green)', fontWeight: 600 }}>✓ On your devices</span>
                  : <button className="btn-ghost" style={{ padding: '5px 10px', fontSize: 11 }} disabled={!!hub.sharing} onClick={() => void hub.shareDoc(p.id, d)}>{hub.sharing ? 'Sharing…' : 'Share to my devices'}</button>)}
              </div>
            </div>
          );
        })}
      </div>
      {open && <DocViewer doc={open} onClose={() => setOpen(null)} />}
    </>
  );
}
